// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgcvqaexvnwwskdhooly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnY3ZxYWV4dm53d3NrZGhvb2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4NTk0MzksImV4cCI6MjA4ODQzNTQzOX0.qoGn8tiDVpdkHboi9vVI3pwP1MR5obpPvPd8RBisZXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false,
  },
  accessToken: async () => {
    const token = localStorage.getItem("custom_auth_token");
    return token || null;
  },
});
